### ISSUE TITLE
Any chance of an updated release?

### ISSUE THREAD

**Issue by SimonDarksideJ** [kuler90/build-unity#2]
It's been over two years since the repository was published, any plans to update the release (of all your packages)?

**Comment by kuler90** [comment]
Hi @SimonDarksideJ,

If you mean outdated node packages, I just took the PR and released a new version. I'm sorry for the delay, just forgot about it. But if you mean development in general, I haven't done Unity development for the last two years. So I can only take PR from the community.

**Comment by SimonDarksideJ** [comment]
Fair enough and I know what you mean @kuler90.
But I meant actually producing a new release, if you do not Release and then update the primary version tag then the action isn't consumed. But I see you have done that now, great work!

**Comment by SimonDarksideJ** [comment]
Can you also ensure the other packages are updated if there are any new changes in development too?  @kuler90

**Comment by kuler90** [comment]
Yes, the node packages have already updated for setup-unity and activate-unity actions
